import "./globals.css";
import localFont from "next/font/local"

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;


const myFont = localFont ({
  src: '../Fonts/segoeuithibd.ttf',
  src: '../Fonts/segoeuithis.ttf',
  // src: '../Fonts/segoeuithisi.ttf',
  // src: '../Fonts/segoeuithisz.ttf',

})



export const metadata = {
  title: "Next-Test",
  description: "Generated by Farshad Ramezani",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className ={myFont.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
